# Generated by Django 3.2.4 on 2021-06-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testdb1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=250)),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Testdb2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=250)),
                ('isOn', models.BooleanField()),
            ],
        ),
    ]
